In [2]:
import tt
import numpy as np

In [9]:
from bilinear_package.src.convolution import approximateConvolution, preciseConvolution

In [20]:
np.random.seed(11)

a = np.random.randint(3, size=(1, 3, 2))
b = np.random.randint(3, size=(2, 3, 1))
tensor = [a, b]

print(a[0, :, :] @ b[:, :, 0])

[[2 0 1]
 [2 0 2]
 [0 0 1]]


In [21]:
tensor = preciseConvolution([a, b], [a, b])
print(np.round(tt.vector.from_list(tensor).full()))

(1, 5, 2)
(1, 5, 2)
(2, 5, 1)
(2, 5, 1)
[[ 4.  0.  4.  0.  1.]
 [ 8.  0. 12.  0.  4.]
 [ 4.  0. 12.  0.  6.]
 [ 0.  0.  4.  0.  4.]
 [ 0. -0.  0.  0.  1.]]
